keycloak:
  image: "jboss/keycloak:4.8.3.Final"
  command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"]
  # command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=export", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config"]
  volumes:
    - ./keycloak-config:/opt/jboss/keycloak/realm-config
    - ./target/magic-link.jar:/opt/jboss/keycloak/standalone/deployments/magic-link.jar
    # - ./data:/opt/jboss/keycloak/standalone/data
  environment:
#    - KEYCLOAK_USER=admin
#    - KEYCLOAK_PASSWORD=password
    - KEYCLOAK_LOGLEVEL=DEBUG
    - KEYCLOAK_THEME_STATIC_MAX_AGE=-1
    - KEYCLOAK_THEME_CACHE_THEMES=false
    - KEYCLOAK_THEME_CACHE_TEMPLATES=false
  ports:
    - 1090:8080
  links:
    - smtp
smtp:
  image: "djfarrelly/maildev"
  ports:
    - 1080:80

